baseURL: https://pacogarcia.de/
languageCode: en-us
title: Paco
theme:  mini

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 3

googleAnalytics: G-LEY0YV34LZ
disqusShortname: pacogarcia

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/xirapo
  twitter: https://twitter.com/isdonquijote
  linkedin: https://www.linkedin.com/in/frankgarcia29/



# personal params
params:
  name: Francisco Garcia
  author: Paco
  bio: Project Coordinator at
  company: Schlesinger Group
  department: IHUT
  description: My Blog
  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: false
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: true
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: true
  customCSS:
    - css/custom.css


